##playbook is a list of plays which is always start with -
- name: ping the node 
  hosts: localhost 
  ##this is the list of tasks/modules/collections
  tasks:
  - name: pinging the server 
  ##this is the map 
    ansible.builtin.ping: