- name: variables from files 
  hosts: localhost ##managing the ansible server itself 
  vars_files:
  - variables.yaml 
  tasks:
  - name: printing the variables
    ansible.builtin.debug:
      msg: "hi im learning {{NAME}},Duration is {{DURATION}},Student is {{STUDENT}}"