- name: install packages
  hosts: localhost
  become: yes
  tasks: 
  - name: install packages
    ansible.builtin.yum:
      name:"{{item-name}}"
      state: installed 
    loop:
    - mailx
    - postfix
