- name: install packages
  hosts: localhost
  become: yes
  tasks: 
  - name: install packages
    ansible.builtin.debug:
      name:"{{item-name}}"
      state: installed 
    loop:
    - nginx
    - postmap
