- name: mongodb
  hosts: localhost
  become: yes
  tasks: 
  - name: copy mongodbrep to yum.repos.d
    ansible.builtin.copy:
      src: mongodb.rep
      dest: /etc/yum.repos.d/mongo.repo
  - name: install mongodb
    ansible.builtin.yum:
       name: mongodb-org
       state: installed 
  - name: Start & Enable MongoDB Service
    ansible.builtin.yum:
       name: mongod
       state: started
       enabled: yes
  - name: enable remote connections to mongodb
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: "127.0.0.1"
      replace: "0.0.0.0"
  - name: restart the Service
    ansible.builtin.yum:
       name: mongod
       state: restarted


